//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_us { get; set; }
        public string nombre_us { get; set; }
        public string apellido_us { get; set; }
        public string rut_us { get; set; }
        public System.DateTime fec_nac_us { get; set; }
        public string correo_us { get; set; }
        public string password { get; set; }
        public Nullable<int> fk_id_cargo { get; set; }
        public Nullable<int> fk_id_fabrica { get; set; }
        public int fk_tipo_us { get; set; }
    
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
